### ISSUE TITLE
Chessboard too big for my screen

### ISSUE THREAD

**Issue by rchastain** [AhmedDawoud3/Chess-Love2D#2]
Hello!

Interesting project. I have just tested it under Linux, and it seems to work. But the chessboard is too big for my PC screen, so I can't see all the pieces. Could you do something for that?

Regards.

Roland

**Comment by totorocodesoften** [comment]
Hello, there is an option for window size in conf.lua, maybe that can help ?

**Comment by rchastain** [comment]
> Hello, there is an option for window size in conf.lua, maybe that can help ?

Thanks. I will take a look.

**Comment by AhmedDawoud3** [comment]
Hi Roland,
Thanks for the issue, I'll try to add the "push library" to make the window resizable and responsive.
changing the window size in conf.lua wouldn't necessarily work because other values are still constant and depend on it.
Thanks
